Added example of lookup value selection and MFA
ryanspain/sample-power-apps-playwright-tests pull request #3
Opened 2022-12-29 12:01 UTC by crisfervil

I'm not sure if this is appropriate, given that this is a basic example, but there it goes anyway. Feel free to reject it if not!

2023-01-01 17:25 UTC, ryanspain requested changes

2023-01-01 17:25 UTC, ryanspain commented on tests/app.spec.js
> +
Works on my machine! Thanks for adding this.

![chrome_vLpOui3J2j](https://user-images.githubusercontent.com/8723433/210179519-bb66ba35-ed4c-4d25-adfb-33834c50ac9e.gif)

2023-01-01 17:26 UTC, ryanspain commented on tests/app.spec.js
> +    await page.waitForNavigation();
Thanks for spotting that. JavaScript is too forgiving 😄

2023-01-01 17:27 UTC, merged

2023-01-01 17:35 UTC, ryanspain commented on tests/app.spec.js
> +    await page.waitForURL(/^(?:(?!login).)*$/,{timeout:60000});
I merged your changes (accidentally) with this and manually dropped the interaction with the **Stay signed in** screen 👍

2023-01-09 12:34 UTC, crisfervil commented
Thanks @ryanspain !! You even added screen recordings!